name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Create keystore directory
        run: mkdir -p android/app/keystore

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          if [ -n "$ENCODED_KEYSTORE" ]; then
            echo "$ENCODED_KEYSTORE" | base64 --decode > android/app/keystore/mpay_keystore.jks
          fi

      - name: Create key.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          if [ -n "$KEYSTORE_PASSWORD" ] && [ -n "$KEY_ALIAS" ] && [ -n "$KEY_PASSWORD" ]; then
            cat <<EOF > android/key.properties
storePassword=$KEYSTORE_PASSWORD
keyPassword=$KEY_PASSWORD
keyAlias=$KEY_ALIAS
storeFile=keystore/mpay_keystore.jks
EOF
          fi

      - name: Build APK
        env:
          VERSION_CODE: 1
          VERSION_NAME: 1.0.0
        run: |
          if [ -f "android/key.properties" ]; then
            flutter build apk --release --build-number=$VERSION_CODE --build-name=$VERSION_NAME
          else
            flutter build apk --debug
          fi

      - name: Create release directory
        run: mkdir -p release

      - name: Copy APK to release directory
        run: cp build/app/outputs/flutter-apk/*.apk release/

      - name: Commit and push APK
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add release/*.apk
          git commit -m "Add built APK [skip ci]" || echo "No changes to commit"
          git push