name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Create keystore directory
        run: mkdir -p android/app/keystore
      
      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          if [ -n "$ENCODED_KEYSTORE" ]; then
            echo "$ENCODED_KEYSTORE" | base64 --decode > android/app/keystore/mpay_keystore.jks
          else
            echo "No keystore found, building debug version"
          fi
      
      - name: Create key.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          if [ -n "$KEYSTORE_PASSWORD" ] && [ -n "$KEY_ALIAS" ] && [ -n "$KEY_PASSWORD" ]; then
            echo "storePassword=$KEYSTORE_PASSWORD" > android/key.properties
            echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
            echo "keyAlias=$KEY_ALIAS" >> android/key.properties
            echo "storeFile=keystore/mpay_keystore.jks" >> android/key.properties
            echo "Key properties file created successfully"
          else
            echo "Missing keystore secrets, building debug version"
          fi
      
      - name: Build APK
        run: |
          if [ -f "android/key.properties" ]; then
            flutter build apk --release
          else
            flutter build apk --debug
          fi
      
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: mpay-plus-release
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: warn
